version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/dapp/frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 0

  - package-ecosystem: pip
    directory: /apps/intelligence
    schedule:
      interval: daily
    open-pull-requests-limit: 0

  - package-ecosystem: gomod
    directory: /apps/api
    schedule:
      interval: daily
    open-pull-requests-limit: 0

  - package-ecosystem: cargo
    directory: /packages/contracts
    schedule:
      interval: daily
    open-pull-requests-limit: 0

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 0
